### ISSUE TITLE
Automounting disabled

### ISSUE THREAD

**Issue by m-emelchenkov** [Parallels/vagrant-parallels#290] opened 2017-02-13 18:50 UTC
If the local path contains Cyrillic symbols and spaces, then Vagrant does not mount "/vagrant" folder with "Automounting disabled" error. If path characters are all English, even with spaces, it works.

**Comment by legal90** [comment] 2020-04-06 15:41
I confirm that this issue still exists in Parallels Desktop 15.1.3. The root cause is the bug in `prlctl` - it doesn't print non-ASCII symbols in Shared Folder host paths in jsonized output.

### Reproduction details

#### 1. Add shared folders with non-ASCII symbols to Vagrantfile:
```
# ...
  config.vm.synced_folder "./Russian_Д", "/media/psf/Russian_Д"
  config.vm.synced_folder "./Estonian_Õ", "/media/psf/Estonian_Õ"
  config.vm.synced_folder "./Swedish_Å", "/media/psf/Swedish_Å"
```

#### 2. Actual result of `vagrant up`:
```
==> default: Mounting shared folders...
    default: /vagrant => /Users/legal/Workspace/vagrant-test-ubuntu
    default: Automounting disabled: /Users/legal/Workspace/vagrant-test-ubuntu/Russian_Д
    default: Automounting disabled: /Users/legal/Workspace/vagrant-test-ubuntu/Swedish_Å
    default: Automounting disabled: /Users/legal/Workspace/vagrant-test-ubuntu/Estonian_Õ
```

#### 3. My findings:
Actually, each shared folder were successfully passed to the VM and they could be mounted manually from the VM shell:
```
vagrant@ubuntu-18:~$ sudo cat /proc/fs/prl_fs/sf_list
List of shared folders:
2: media_psf_Russian_Д rw
3: media_psf_Estonian_Õ rw
4: media_psf_Swedish_Å rw
1: vagrant rw

vagrant@ubuntu-18:~$ sudo mkdir -p /media/psf/Russian_Д

vagrant@ubuntu-18:~$ sudo mount -t prl_fs media_psf_Russian_Д /media/psf/Russian_Д
```

The output of `prlctl list -i <id>` show everything correct:
```
Host Shared Folders: (+)
  media_psf_Russian_Д (+) path='/Users/legal/Workspace/vagrant-test-ubuntu/Russian_Д' mode='rw'
  media_psf_Estonian_Õ (+) path='/Users/legal/Workspace/vagrant-test-ubuntu/Estonian_Õ' mode='rw'
  media_psf_Swedish_Å (+) path='/Users/legal/Workspace/vagrant-test-ubuntu/Swedish_Å' mode='rw'
  vagrant (+) path='/Users/legal/Workspace/vagrant-test-ubuntu' mode='rw'
```

But the json-ized output `prlctl list -i <id> --json`, which our provider uses as source of truth, just drops the non-ASCII symbols (but only in host path 🤷‍♂):
```json
		"Host Shared Folders": {
			"enabled": true,
			"media_psf_Russian_Д": {
				"enabled": true,
				"path": "\/Users\/legal\/Workspace\/vagrant-test-ubuntu\/Russian_",
				"mode": "rw"
			},
			"media_psf_Estonian_Õ": {
				"enabled": true,
				"path": "\/Users\/legal\/Workspace\/vagrant-test-ubuntu\/Estonian_",
				"mode": "rw"
			},
			"media_psf_Swedish_Å": {
				"enabled": true,
				"path": "\/Users\/legal\/Workspace\/vagrant-test-ubuntu\/Swedish_",
				"mode": "rw"
			},
			"vagrant": {
				"enabled": true,
				"path": "\/Users\/legal\/Workspace\/vagrant-test-ubuntu",
				"mode": "rw"
			}
		},
```
That's why the provider fail's to find the associated `id` here
https://github.com/Parallels/vagrant-parallels/blob/5e8b82d6b099372ccbe794c5c1cf4198285b2114/lib/vagrant-parallels/synced_folder.rb#L53-L55
and then it falls back to "Automounting disabled" here:
https://github.com/Parallels/vagrant-parallels/blob/5e8b82d6b099372ccbe794c5c1cf4198285b2114/lib/vagrant-parallels/synced_folder.rb#L74-L78

@romankulikov Do you know if it's possible to fix that issue on `prlctl` side?

**Comment by romankulikov** [comment] 2020-04-11 13:22
Confirm the problem. Will investigate.

**Comment by mpdude** [comment] 2020-08-24 11:15
Similar issue that might be related:

When I use `config.vm.synced_folder "/some/host/path", "/some/guest/path"` in the `Vagrantfile` and then create a directory containing German umlauts (probably cyrillic chars would do as well) in `/some/host/path`, this directory does *not* show up in the guest VM.

**Comment by mpdude** [comment] 2020-08-24 11:17
... so it's not an issue with `prlctl` itself or with the guest tools, but a more low-level issue on the guest side?

**Comment by mpdude** [comment] 2020-08-24 11:44
A co-worker is running Parallels Version 14.1.2 (45479) and Parallels Tools 14.1.45479. He's also on an older version of OS X and might not be using APFS as I am.

For him, it seems to work:

```
/var/www/$ ll src/styleguide/Seiten/
total 0
drwxr-xr-x 1 vagrant vagrant 160 Aug 24 11:29  ./
drwxr-xr-x 1 vagrant vagrant 192 Aug 24 08:17  ../
drwxr-xr-x 1 vagrant vagrant  96 Aug 24 10:40  Förderung/
drwxr-xr-x 1 vagrant vagrant  96 Aug 24 10:29  News/
drwxr-xr-x 1 vagrant vagrant  96 Aug 24 10:36 'Über uns'/
```

Could you please advise if 
- this should be an issue on its own?
- which details you need to confirm
- this might be a regression in Parallels Tools and it would be worth trying a downgrade?

**Comment by legal90** [comment] 2020-08-24 11:50
@mpdude It works for him because the host path does not have non-ASCII characters (`<something>/src/styleguide/Seiten`).

> ... so it's not an issue with prlctl itself or with the guest tools, but a more low-level issue on the guest side?

No, that look exactly the same as was I described with details above. That is a bug of `prlctl`, which prevents Shared Folder from working if there full path to it on the host side contains non-ASCII characters.

**Comment by mpdude** [comment] 2020-08-24 13:12
We might be describing different issues then.

Both my coworker and me are using `config.vm.synced_folder "~/Projects", "/var/www"` in our `Vagrantfile`s. 

If a subdirectory of `~/Projects` on the host contains directories with non-ascii chars (like the `src/styleguide/Seiten/` example given above, which contains sub-directories `Über uns` or `Förderung`), those directories are not visible inside the guest VM.

I am afraid this has nothing to do with automounting and/or `prlctl` listing those directories.

**Comment by mpdude** [comment] 2020-09-04 10:18
It seems the update to Parallels 16.0.0 and to Parallels Tools 16.0.48916 solves at least "my" issue.

**Comment by romankulikov** [comment] 2020-12-11 12:11
> Confirm the problem. Will investigate.

Terribly sorry for no updates from my side. The issue as described in [initially](https://github.com/Parallels/vagrant-parallels/issues/290#issuecomment-609872292 ) is fixed in Parallels Desktop 16. It is on the host side.

**Comment by legal90** [comment] 2020-12-13 20:27
Yes, I confirm it's fixed in Parallels Desktop 16 👍 
Though, there could still be an error caused by the the encoding issue:
```
$ vagrant up

<... skipped ...>

==> default: Mounting shared folders...
    default: /vagrant => /Users/legal/Workspace/vagrant-parallels
    default: /var/www/path => /Users/legal/Workspace/vagrant-parallels
    default: /media/psf/Russian_Д => /Users/legal/Workspace/vagrant-test-ubuntu/Russian_Д
==> default: Forcing shutdown of VM...
==> default: Destroying VM and associated drives...
==> default: Destroying unused networking interface...
Traceback (most recent call last):
	106: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
	105: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/machine.rb:201:in `action'

<... skipped ...>

	  4: from /Users/legal/.vagrant.d/gems/2.6.6/gems/vagrant-parallels-2.1.0/lib/vagrant-parallels/synced_folder.rb:72:in `block in enable'
	  3: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/guest.rb:43:in `capability'
	  2: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/capability_host.rb:111:in `capability'
	  1: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/capability_host.rb:111:in `call'
/Users/legal/.vagrant.d/gems/2.6.6/gems/vagrant-parallels-2.1.0/lib/vagrant-parallels/guest_cap/linux/mount_parallels_shared_folder.rb:40:in `mount_parallels_shared_folder': incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)
```

I don't know the exact source of it, but it's fixed in #377

**Closed** 2020-12-14 09:03 UTC
Labels: upstream/parallels

**Comment by BenceSzalai** [comment] 2021-03-01 17:15
Hi! Do you have any plan about releasing the fix, or is there a way to use the latest master instead of [v2.1.0](https://github.com/Parallels/vagrant-parallels/releases/tag/v2.1.0) with Vagrant?

**Comment by legal90** [comment] 2021-03-01 17:57
Hi @BenceSzalai,
I'm sorry for a long delay with the release. I'll do my best to cut a new release during this week.

Using the lates master is also possible. Please, check the section ["Building Provider from Source"](https://github.com/Parallels/vagrant-parallels/blob/master/CONTRIBUTING.md#building-provider-from-source)

**Comment by legal90** [comment] 2021-03-03 19:40
The fix is released in [v2.2.0](https://github.com/Parallels/vagrant-parallels/releases/tag/v2.2.0)

**Comment by m-emelchenkov** [comment] 2021-04-30 18:11
I tried today version 2.2.1 with Vagrant 2.2.16 and faced the issue: i.e. I have a path `/Users/Mikhail/Жена/Веб-сайт/www/tools`, and run `vagrant up` from there. So I have mounted folder under /vagrant. Instead it mounts `/Users/Mikhail/Жена`. It lost part of path somewhere. I am not familiar with Vagrant architecture, I did only basic debugging (debug `puts`) and found that plugin's function `def enable(machine, folders, _opts)` in `synced_folder.rb` already receives broken paths. So maybe Vagrant do path handling wrong somewhere. I hope those developers here who know Vagrant architecture well will tell where is the problem. Thanks!!!

**Comment by legal90** [comment] 2021-05-12 06:06
@m-emelchenkov If that is still actual for you - could you please create a new issue and provide the sample of Vagrantfile you are using? Thanks!

**Comment by m-emelchenkov** [comment] 2021-05-12 08:59
> @m-emelchenkov If that is still actual for you - could you please create a new issue and provide the sample of Vagrantfile you are using? Thanks!

https://github.com/Parallels/vagrant-parallels/issues/388
