### ISSUE TITLE
Can't detect parallels tools on fresh, current box

### ISSUE THREAD

**Issue by bbock** [Parallels/vagrant-parallels#255] opened 2016-03-24 09:10 UTC
```
# vagrant init parallels/ubuntu-14.04
...
# vagrant up
Bringing machine 'default' up with 'parallels' provider...
==> default: Registering VM image from the base box 'parallels/ubuntu-14.04'...
==> default: Cloning new virtual machine...
==> default: Unregistering the box VM image...
==> default: Setting the default configuration for VM...
==> default: Checking if box 'parallels/ubuntu-14.04' is up to date...
==> default: Setting the name of the VM: vagrant-test_default_1458809875179_78285
==> default: Preparing network interfaces based on configuration...
    default: Adapter 0: shared
==> default: Clearing any previously set network interfaces...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 10.211.55.24:22
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection refused. Retrying...
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for Parallels Tools installed on the VM...
==> default: Parallels Tools were not detected on this VM! They are required
==> default: for shared folders, time sync and more. If shared folders are not
==> default: working on this machine, please install Parallels Tools within the
==> default: virtual machine and reload your VM.
==> default: Mounting shared folders...
    default: /vagrant => /Users/bernhard/Desktop/vagrant-test
Failed to mount folders in Linux guest. This is usually because
the "prl_fs" file system is not available. Please verify that
Parallels Tools are properly installed in the guest and
can work properly. If so, the VM reboot can solve a problem.
The command attempted was:

mount -t prl_fs -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3` vagrant /vagrant
mount -t prl_fs -o uid=`id -u vagrant`,gid=`id -g vagrant` vagrant /vagrant
```

Version information:
- vagrant 1.8.1
- Parallels Desktop 11.1.3 (32521) Pro Edition
- vagrant-parallels plugin 1.6.2
- OS X 10.11.3

Rebooting the box does not help. As I understand the documentation, a manual installation of tools should not be necessary?!

**Comment by benjifisher** [comment] 2016-03-24 12:56
I am having the same problem.  The parallels/ubuntu-12.04 box works fine, so it seems there is something wrong with the latest parallels/ubuntu-14.04 box.

Here is a little more info, in the hope that it will help diagnose the issue.  When I have

```ruby
  config.vm.provider "parallels" do |prl|
    prl.check_guest_tools = true
    prl.update_guest_tools = true
  end
```

in my Vagrantfile, then I get this as part of the output:

```
==> devstack: Checking for Parallels Tools installed on the VM...
==> devstack: Parallels Tools were not detected on this VM! They are required
==> devstack: for shared folders, time sync and more. If shared folders are not
==> devstack: working on this machine, please install Parallels Tools within the
==> devstack: virtual machine and reload your VM.
==> devstack: Installing the proper version of Parallels Tools. This may take a few minutes...
==> devstack: Parallels Tools have been installed. Rebooting the VM...
```

There is no pause between the last two lines.  At the end of the process, the tools have not been installed and the shared directories have not been mounted.

**Comment by legal90** [comment] 2016-03-24 13:02
Yes, I confirm - Parallels Tools are broken in the following boxes:
 - `parallels/ubuntu-14.04` v1.0.11
 - `parallels/ubuntu-14.04-i386` v1.0.11

I've just revoked these versions from Atlas at the moment, so please downgrade to the previous one (1.0.10):
```
vagrant box remove parallels/ubuntu-14.04 --box-version 1.0.11
vagrant box update --box parallels/ubuntu-14.04
```

**Comment by bbock** [comment] 2016-03-24 13:11
downgrade works, thanks a lot for the quick reaction!

**Comment by benjifisher** [comment] 2016-03-24 13:18
Ditto.

**Comment by fmalee** [comment] 2016-04-10 22:52
OMG，I spent a lot of time on this issue，this is not my problem!!!
I use Packer to maked Ubuntu 14.04.4，now,how can i fix this?
Problems caused by the Linux kernel？
I'm really troubled，THX~

**Comment by legal90** [comment] 2016-04-12 08:24
@fmalee I'm sorry about that. :(
The issue was caused by the fact that during the box build, Linux kernel has been updated _after_ Parallels Tools installation. Usually, it requires Parallels Tools to be re-installed. Otherwise, some kernel modules became not working.

It was fixed on the bento's side (we use it to build our boxes): https://github.com/chef/bento/pull/551
The updated boxes `parallels/ubuntu-14.04` and `parallels/ubuntu-14.04-i386` will be released soon.

**Comment by legal90** [comment] 2016-04-12 13:47
Boxes have been fixed:
`parallels/ubuntu-14.04` [v1.0.12](https://atlas.hashicorp.com/parallels/boxes/ubuntu-14.04/versions/1.0.12)
`parallels/ubuntu-14.04-i386` [v1.0.12](https://atlas.hashicorp.com/parallels/boxes/ubuntu-14.04-i386/versions/1.0.12)

**Closed by legal90** 2016-04-12 13:47 UTC
Labels: upstream/parallels
