### ISSUE TITLE
Can't load centos with Parallels 11.2

### ISSUE THREAD

**Issue by raztus** [Parallels/vagrant-parallels#265] opened 2016-06-17 22:18 UTC
Attempting to use centos, the machine boot spins until timeout. This happens with different centos vagrant boxes I've tried (parallels/centos-7.1, parallels/centos-7.2, bento/centos-7.2). It seems to be an issue with having two `private_network` configs, as it works if I remove either one of them. It also seems to be centos only, as replacing only the box with `parallels/ubuntu-14.04` succeeds.

Vagrant file, in its entirety:

```
Vagrant.configure("2") do |config|
  config.vm.box = "parallels/centos-7.2"
  config.vm.network "private_network", ip: "10.37.132.10"
  config.vm.network "private_network", ip: "10.37.132.20"
end
```

Parallels and machine info:

```bash
$ prlctl --version
prlctl version 11.2.0 (32581)
```

```bash
$ prlsrvctl info
ID: {redacted}
Hostname: 127.0.0.1
Version: Desktop 11.2.0-32581
OS: Mac OS X 10.11.5(15F34)
Started as service: off
VM home: /Users/myusername/Documents/Parallels
Memory limit: auto
Minimal security level: low
Manage settings for new users: allow
CEP mechanism: off
Backup path: /Users/Shared/Parallels/Backups
Backup temporary directory: 
Backup timeout: 3600
Default encryption plugin: <parallels-default-plugin>
Verbose log: off
Allow mobile clients: off
Proxy connection state: disconnected
Direct connection: off
Log rotation: on
Advanced security mode: off
Proxy manager URL: https://pax-manager.myparallels.com/xmlrpc/rpc.do
Web portal domain: parallels.com
Host ID: 
Allow attach screenshots: on
License: state='valid' key='redacted' restricted='false'
Hardware Id: {redacted}
Signed In: no
Hardware info:
     hdd  APPLE SSD SM0512G (disk0)                '/dev/disk0'
hdd-part  EFI System Partition                     '/dev/disk0s1'
hdd-part  Customer                                 '/dev/disk0s2'
hdd-part  Recovery HD                              '/dev/disk0s3'
hdd-part  BOOTCAMP                                 '/dev/disk0s4'
   cdrom  Default CD/DVD-ROM                       'Default CD/DVD-ROM'
     net  Wi-Fi                                    'en0'
     net  en1                                      'en1'
     net  en2                                      'en2'
     net  p2p0                                     'p2p0'
     net  awdl0                                    'awdl0'
     net  Thunderbolt Bridge                       'bridge0'
     net  vboxnet1                                 'vboxnet1'
     net  vnic0                                    'vnic0'
     net  vnic1                                    'vnic1'
     net  vnic2                                    'vnic2'
     usb  Apple Internal Keyboard / Trackpad       '14400000|05ac|0274|full|KM|D3H5275Z641GHMFA11FS'
     usb  Apple Bluetooth USB Host Controller #2   '14300000|05ac|8290|full|KM|Empty'
  serial  /dev/cu.Bluetooth-Incoming-Port          '/dev/cu.Bluetooth-Incoming-Port'
```

Debug-level output from `vagrant up`:

[parallels_centos7.2_output.txt.zip](https://github.com/Parallels/vagrant-parallels/files/321324/parallels_centos7.2_output.txt.zip)

**Comment by legal90** [comment] 2016-06-18 19:28
Hi, @raztus, 
Thank you for pointing on this issue! 
I confirm - it is reproducible on CentOS 7.* boxes by `parallels/` and `bento/`. Actually, they are built from the same templates - [bento](https://github.com/chef/bento).

Seems like this issue is caused by Network Manager (appeared in RHEL/CentOS 7), which does something weird with network connection naming:
```
# nmcli d
DEVICE  TYPE      STATE         CONNECTION
eth1    ethernet  connected     eth0
eth0    ethernet  disconnected  --
eth2    ethernet  disconnected  --
lo      loopback  unmanaged     --

# nmcli c
NAME  UUID                                  TYPE            DEVICE
eth0  5fb06bd0-0bb0-7ffb-45f1-d6edd65f3e03  802-3-ethernet  eth1
```
The similar issue, with Virtualbox : https://github.com/chef/bento/issues/388

However, it is already fixed in the box `boxcutter/centos72` ([repo](https://github.com/boxcutter/centos)). I've checked it with Vagrantfile you've mentioned above - everything works fine with parallels provider. 

I think we should port the commit https://github.com/boxcutter/centos/commit/be4174ea6e8c053d25f970d524d1801c6b21c55f to the Bento templates and rebuild our boxes.

**Comment by legal90** [comment] 2016-08-02 19:26
It has been fixed in boxes:
* [`parallels/centos-7.2`](https://atlas.hashicorp.com/parallels/boxes/centos-7.2/) v1.0.3+
* [`bento/centos-7.2`](https://atlas.hashicorp.com/bento/boxes/centos-7.2/) v2.2.8+

**Closed by legal90** 2016-08-02 19:26 UTC
