### ISSUE TITLE
update_guest_tools 

### ISSUE THREAD

**Issue by Tanzy** [Parallels/vagrant-parallels#274] opened 2016-08-18 14:58 UTC
Getting an error when using update_guest_tools with Parallels 12

**Comment by legal90** [comment] 2016-08-18 15:25
Could you please elaborate, what's the error output you've to get? What box name and version do you use?

Actually, it might be expected because of major changes in guest tools between Parallels Desktop 11 and 12. I'll try to build new boxes with latest Parallels Tools as soon as possible.

**Comment by Tanzy** [comment] 2016-08-18 15:34
Sorry, just put this issue in quickly, below is the output that I'm getting

```
==> default: Checking for Parallels Tools installed on the VM...
==> default: Parallels Tools installed on this VM are outdated! In most cases
==> default: this is fine but in rare cases it can cause things such as shared
==> default: folders to not work properly. If you see shared folder errors,
==> default: please update Parallels Tools within the virtual machine and
==> default: reload your VM.
==> default: Installing the proper version of Parallels Tools. This may take a few minutes...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

ptiagent-cmd --info

Stdout from the command:
```

I'm using the parallels/ubuntu-14.04 box

Below is a link to the Vagrant config that I'm using

[https://bitbucket.org/tanzy/vagrant-dev-machine](https://bitbucket.org/tanzy/vagrant-dev-machine) This box works fine when I turn off the auto update of the Guest tools

**Comment by legal90** [comment] 2016-08-19 09:12
@Tanzy Wat box version do you use? It could be found by running this command:
```
vagrant box list | grep "parallels/ubuntu-14.04"
```

I've tried to reproduce it with `1.0.12` (Parallels Tools v11.1.3) and `1.0.14` (Parallels Tools v11.2.1), in both cases Parallels Tools have been upgraded to 12.0.0 without error.

**Comment by Tanzy** [comment] 2016-08-19 09:16
mm, I'm using 

box = parallels/ubuntu-14.04 (parallels, 1.0.14)

plugin = vagrant-parallels (1.6.3)

Parallels Desktop = Pro Edition Version 12.0.0 (41273)

**Comment by romankulikov** [comment] 2016-08-20 13:52
It would be great to see tail of `/var/log/parallels-tools-install.log` from the guest.

**Comment by legal90** [comment] 2016-08-22 07:46
@Tanzy FYI: We've built and released version v2.0.0 of [every our currently supported boxes](https://github.com/Parallels/vagrant-parallels/wiki/Available-Vagrant-Boxes), including `parallels/ubuntu-14.04`. There are Parallels Tools v12.0.0 shipped inside, so now it should work fine for you. Just update the box:

```
vagrant box update
```

But it still would be great to get `/var/log/parallels-tools-install.log` from your old box, as @romankulikov requested above. It might help us to investigate why Parallels Tools upgrade has failed in your case. Thank you!

**Comment by Tanzy** [comment] 2016-08-22 10:27
Thanks for the update, I finally go the chance to try again today to obtain the log file. Destroyed my Vagrant machine and rebuilt it, unfortunately (fortunately??) I'm not able to reproduce it now, still using the same box.

**Comment by legal90** [comment] 2016-09-06 07:28
OK, then I close the issue.
Let us know if you run into this again.

**Closed by legal90** 2016-09-06 07:28 UTC
Labels: waiting-reply
