### ISSUE TITLE
Cannot connect Hard Drive 0

### ISSUE THREAD

**Issue by SurferL** [Parallels/vagrant-parallels#319] opened 2018-03-23 09:26 UTC
### Version Info:
`Packer: 1.2.1`
`Parallels Desktop 13`
`Vagrant: 2.0.3`
`vagrant-parallels (1.7.8)`

I'm having the same issue seen in: https://github.com/Parallels/vagrant-parallels/issues/192, but previously wasn't having this error.

I'm unsure whether or not this is due to the mentioned at https://github.com/hashicorp/packer/issues/1590, and was wondering if someone can clarify?

I don't think it is, as I do have longer VM names used around which work. In this build, I have a ubuntu image which works (vm name of `sdk-ubuntu-dev.box`, while I have a Mac OSX and Windows VM which doesn't work and has the `Cannot connect to Hard Drive 0` error.

Any help would be greatly appreciated! :) 

### Packer scripts
```
...
{
  "type": "parallels-pvm",
  "parallels_tools_flavor": "mac",

  "source_path": "{{ user `parallels_base_image` }}",
  "output_directory": "{{ user `parallels_output_dir` }}",

  "ssh_username":	"{{ user `username` }}",
  "ssh_password":	"{{ user `password` }}",

  "shutdown_command": "echo '{{ user `password` }}' | sudo -S shutdown -h now",
  "shutdown_timeout": "10m",

  "vm_name": "sdk-mac-dev"
}

...

"post-processors": [
  {
    "type": "vagrant",
    "output": "{{ user `vagrant_output_dir` }}/sdk-mac-dev.box",
    "only": ["parallels-pvm"]
  }
]
```

### Vagrantfile
```
  config.vm.define "mac" do |subconfig|

    subconfig.vm.box = "sdk-mac-dev.box"

    subconfig.vm.boot_timeout = 1200
    subconfig.vm.graceful_halt_timeout = 1200

    subconfig.ssh.username = "vagrant"
    subconfig.ssh.password = "vagrant"

    subconfig.vm.provider "parallels" do |prl|
      prl.name = "sdk-mac-dev"
      prl.update_guest_tools = true
    end
  end
```

### Folder structure
In `~/.vagrant.d/boxes/sdk-mac-dev.box/`
```
sdk-mac-dev.box SurferL$ tree
.
└── 0
    └── parallels
        ├── Vagrantfile
        ├── metadata.json
        └── sdk-mac-dev.pvm
            ├── NVRAM.dat
            ├── VmInfo.pvi
            ├── config.pvs
            └── harddisk.hdd
                ├── DiskDescriptor.xml
                ├── harddisk.hdd
                ├── harddisk.hdd.0.{5fbaabe3-6958-40ff-92a7-860e329aab41}.hds
                └── harddisk.hdd.drh

4 directories, 9 files
```

**Comment by romankulikov** [comment] 2018-03-23 17:14
Can you please generate problem report in Parallels Desktop and its id here? For this run in terminal `prlsrvctl problem-report --send`.

**Comment by SurferL** [comment] 2018-03-23 17:24
`The problem report was successfully sent with id: 248114003`

Although I'm not sure if this is the correct one, but it should be!

**Comment by Baune8D** [comment] 2018-03-25 19:14
Same error here! Cannot boot Windows VM, error "Cannot connect Hard Drive 1"

Same software versions as OP. This happens on a brand new install of High Sierra.
I am lost right now as i cannot boot up my work environment.

**Comment by Baune8D** [comment] 2018-03-25 21:51
@SurferL I just solved my problem, which seems similar to yours.

See: https://github.com/hashicorp/vagrant/issues/9555
and: https://github.com/hashicorp/packer/issues/5990

Workaround for me is using Packer 1.1.3 to build the .box file.

**Comment by SurferL** [comment] 2018-03-26 12:56
@Baune8D Thank you for posting that - I've tried using Packer 1.1.3 to rebuild the boxes, however it still isn't working :( What version of Vagrant and vagrant-packer plugin are you using? I'm on an upgraded install of High Sierra fwiw...

@romankulikov I've generated a new problem report with id: `248516165`, which I built using Packer 1.1.3 instead, if this of use!

**Comment by Baune8D** [comment] 2018-03-26 13:03
@Surfer When i built the Packer box with 1.2.1, the box file would have a size of approximatly 5 gb as expected. But after Vagrant imported the box the hdd file would be less than 1 mb. So that is the reason Parallels complained about the hard disk file.

It would be pretty easy to see if you have the same problem as me, just check the size of the imported .hdd file in ~ /.vagrant.d/boxes

Software i was using was:
macOS 10.13.3 (Clean install)
Parallels 13.3.0
Vagrant 2.0.3
Packer 1.2.1 (This is was the culprint for me)

**Comment by SurferL** [comment] 2018-03-26 16:42
@Baune8D I wiped Packer entirely from the System, and reinstalled from https://releases.hashicorp.com/packer/1.1.3/packer_1.1.3_darwin_amd64.zip (placing it in `/usr/local/bin`)

I thought it was a bit more promising as there is the harddisk listed:

```
$ tar -tvf sdk-mac.box 
-rw-r--r--  0 501    20        180 26 Mar 17:25 Vagrantfile
-rw-r--r--  0 501    20         25 26 Mar 17:25 metadata.json
-rw-r--r--  0 501    20      65536 26 Mar 17:24 sdk-mac.pvm/NVRAM.dat
-rw-r--r--  0 501    20       7224 26 Mar 17:24 sdk-mac.pvm/VmInfo.pvi
-rw-r--r--  0 501    20      26381 26 Mar 17:24 sdk-mac.pvm/config.pvs
-rw-r--r--  0 501    20       1710 26 Mar 17:24 sdk-mac.pvm/harddisk.hdd/DiskDescriptor.xml
-rw-r--r--  0 501    20          0 26 Mar 17:24 sdk-mac.pvm/harddisk.hdd/harddisk.hdd
-rw-r--r--  0 501    20 17578328064 26 Mar 17:25 sdk-mac.pvm/harddisk.hdd/harddisk.hdd.0.{5fbaabe3-6958-40ff-92a7-860e329aab41}.hds        
-rw-r--r--  0 501    20        7680 26 Mar 17:25 sdk-mac.pvm/harddisk.hdd/harddisk.hdd.drh
```
I'm a tad confused with `/harddisk.hdd/harddisk.hdd` being `0`, but I mean, the other harddisk is there.

But then doing:
```
ls -l ~/.vagrant.d/boxes/sdk-mac.box/0/parallels/sdk-mac.pvm/
total 256
-rw-r--r--  1 user  group  65536 26 Mar 14:04 NVRAM.dat
-rw-r--r--  1 user  group   7224 26 Mar 14:04 VmInfo.pvi
-rwxr--r--  1 user  group  26375 26 Mar 17:33 config.pvs
-rwxr--r--  1 user  group  26375 26 Mar 17:33 config.pvs.backup
drwxr-xr-x  6 user  group    192 26 Mar 14:06 harddisk.hdd
```
shows that it looks like it's Vagrant which is unpacking it correctly? 

Any other ideas?

**Comment by romankulikov** [comment] 2018-03-30 16:12
@SurferL, thank you for your problem reports! Unfortunately I cannot be 100% sure but _it looks like_ that your hard disk is going fail. There're system IO errors in logs. Can you please try to reproduce the problem working with VM-s one any other disk (external, for example)?

**Comment by legal90** [comment] 2018-03-31 08:37
That is a bug in `libarchive`, which affected Go compiler 1.10: https://github.com/golang/go/issues/24599#issuecomment-377351717
Then it affects Packer 1.2.1 and 1.2.2, which were compiled with Go 1.10: https://github.com/hashicorp/packer/issues/5990#issuecomment-372331979

It was worked around on Packer's side: https://github.com/hashicorp/packer/pull/6084
@SurferL, @Baune8D so you should try to use Packer 1.1.3 until the next version (> 1.2.2) is released

**Comment by legal90** [comment] 2018-04-28 20:49
Packer v1.2.3 has been released recently. This issue should be fixed there.

**Closed by legal90** 2018-04-28 20:49 UTC
