### ISSUE TITLE
Broken shared file reading

### ISSUE THREAD

**Issue by piratadelfuturo** [Parallels/vagrant-parallels#335] opened 2018-12-21 19:08 UTC
I am using Laravel Homestead and since I updated to Parallels 14 there has been a frustrating strange behavior in php, the files seems to be corrupted but only while read by php, bash shows the code is correct and the files both in host and guest seem fine, I am getting this error reporting unwanted characters in different files only in the guest:

Warning: Unexpected character in input:  ' in /home/vagrant/nazaret.design.sulu/vendor/twig/twig/lib/Twig/ExtensionSet.php on line 486
PHP Warning:  Unexpected character in input:  ' in /home/vagrant/nazaret.design.sulu/vendor/twig/twig/lib/Twig/ExtensionSet.php on line 486

Warning: Unexpected character in input:  ' in /home/vagrant/nazaret.design.sulu/vendor/twig/twig/lib/Twig/ExtensionSet.php on line 486
        18:40:26 ERROR     [console] Error thrown while running command "sulu:build dev". Message: "syntax error, unexpected ''Twig_' (T_ENCAPSED_AND_WHITESPACE)" ["exception" => ParseError { …},"command" => "sulu:build dev","message" => "syntax error, unexpected ''Twig_' (T_ENCAPSED_AND_WHITESPACE)"]

        In Core.php line 1613:

          Parse error: syntax error, unexpected ''Twig_' (T_ENCAPSED_AND_WHITESPACE)

I tried in different machines and reinstalling several times and haven't found a clue, only rolling back to Parallels 13 works, I reported to Parallels support but they have no clue or feedback about how to address this.

Has anyone experienced this?

**Comment by romankulikov** [comment] 2018-12-23 18:53
Pretty the same addressed in #330.

**Comment by legal90** [comment] 2020-04-05 08:51
Closing this as duplicate of #330

**Closed by legal90** 2020-04-05 08:51 UTC
