### ISSUE TITLE
Issues after upgrading to parallels 14 (Automounting disabled)

### ISSUE THREAD

**Issue by TNAJanssen** [Parallels/vagrant-parallels#330] opened 2018-10-22 08:42 UTC
Hi All,
Since parallels 14 is have some issues with the shared folders, when i change a file i get this error from PHP:

PHP Warning:  Unexpected character in input:  '

It looks like the endings are converted, but when i downgrade the parallels tools to the version included with parallels 13 it works perfectly.

Does anybody have an idea?

Thanks!

**Comment by gandalfar** [comment] 2018-10-22 13:40
I think it's something that changed in the last few days. Since this error started appearing for me today, while I had this setup with Parallels 14 for longer.

**Comment by TNAJanssen** [comment] 2018-10-22 13:42
If you install the parallels tools from version 13 (use parallels desktop 14) it works great

**Comment by gandalfar** [comment] 2018-10-22 15:08
Lets give a bit more context here for maintainers:

Parallels Tools: 14.0.45154
Parallels 14 for Mac Pro: Version 14.0.1 (45154)

Default vagrant sync mode

**Comment by gandalfar** [comment] 2018-10-23 09:21
Since I don't have easy access to version 13 tools, I've dug up to find the problem.

The issue, at least in my case, is that I had 'auto-save' turned on in PHP Storm. For whatever reason, syncing is much slower in Parallels 14 and that meant that I kept seeing partially/incorrectly synced files in my vagrant. Turning off auto-save is a temporary workaround for this issue, for me.

**Comment by romankulikov** [comment] 2018-10-23 10:55
In Parallels Tools version 14.0.x in made significant changes and improvements in Shared Folders. Unfortunately they brought some serious issues as well. I expect 14.1.x release be much better.

@TNAJanssen, @gandalfar, can you please provide some narrow test case or steps to reproduce the issue you suffer?

**Comment by gandalfar** [comment] 2018-10-23 10:57
Any ideas on how would one approach that? I guess, I could write a watcher that would inspect shared folder and compare some checksums etc. but this sounds like too much work. Do you have any simpler approaches - since it seems (at least to me) that it's a timing/performance thing?

**Comment by romankulikov** [comment] 2018-10-23 12:21
You've mentioned changes in PHP Storm are synced slowly: can you provide:
* code base to test;
* example of changes;
* approximate timing of these changes to sync  in Parallels Tools versions 13 and 14.
In other words something for us to try to reproduce the problem.

**Comment by gandalfar** [comment] 2018-10-25 11:49
Steps to reproduce at least on my system:

1. Install vvv: ( https://varyingvagrantvagrants.org/docs/en-US/installation/ )

After running `vagrant up` first time, you'll need to do `vagrant reload` as it crashes due to the #325 
2. Visit `http://local.wordpress.test/` and confirm the WP site loads. In Chrome, "View Source"

3. With phpstorm open: `~/vagrant-local/www/wordpress-default/public_html/wp-content/themes/index.php`

On line 30: add a comment:
`<?php // example comment here ?>`

4. Quickly refresh your "View source" tab, you should see a number of: 
```
-- | --
  | <b>Warning</b>:  Unexpected character in input:  ' in <b>/srv/www/wordpress-default/public_html/wp-content/themes/twentyseventeen/index.php</b> on line <b>68</b><br />
```
on top.

5. Wait a few seconds and refresh again. The input errors will now be gone.

Versions:

Vagrant: 2.2.0
VVV: git commit $6661ad660088f0ac64fdc1eb57adeae814154f36
Env variable: `VAGRANT_DEFAULT_PROVIDER=parallels`

➜  vagrant-local git:(master) vagrant plugin list
vagrant-hostsupdater (1.1.1.160, global)
  - Version Constraint: > 0
vagrant-parallels (1.7.8, global)
  - Version Constraint: > 0
vagrant-share (1.1.9, global)
  - Version Constraint: > 0

Parallels desktop 14 Pro for mac: 45154
PHP Storm: 2018.2.5

**Comment by romankulikov** [comment] 2018-10-25 21:28
@gandalfar, thanks a lot! Will try to investigate.

**Comment by gandalfar** [comment] 2018-11-01 16:14
Btw, for anyone looking at this issue, before it's fixed upstream - it seems that changing sync method to NFS, makes sync work better:

`config.vm.synced_folder "wp", "/var/wp", type: "nfs"`

**Comment by rtshome** [comment] 2018-11-27 06:34
Same problem for me too. As a short term solution, I switched back to Parallels 13 to solve the problem .
Does the latest versions of Parallels (14.1.0.45387) and the vagrant plugin (2.0.0) solve the problem?

**Comment by stephenreay** [comment] 2018-11-27 21:39
This is still an issue in v14.1.0 (45387)

It's very reproducible for me - any change made in the host environment causes 'corruption' of the file in the guest environment, under particular calls.

e.g. a basic file with a simple echo statement invoked via three methods:

    php foo.php
    php < foo.php
    cat foo.php | php

All work fine the first time. After modifying the file on the host, the first two methods produce a syntax error, or if you try to produce highlighted source (`php -s`), gibberish followed by a segfault, while `cat` accesses the file fine.

I understand that bugs happen, but this has been dragged out for months - I reported an issue about this to Parallels support at the end of *August*, and after weeks of zero updates, they *assured* me it would be fixed in the upcoming release, which finally arrived a few days ago... and it's not fixed.

@romankulikov What do you need from us to debug this issue, and fix it? The amount of lost time trying to work around this issue (not to mention trying to explain it to support staff) would pay for 5 years worth of subscription renewals at this point, so *please* tell me what you need to fix this, finally.

**Comment by stephenreay** [comment] 2018-11-27 22:01
To confirm what was reported before - downgrading to v13 tools *does* work

For those interested in this route, try the following:

- Download the v13 installer DMG, and mount (open) it.
- Copy the file `"/Volumes/Parallels Desktop 13/Parallels Desktop.app/Contents/Resources/Tools/prl-tools-lin.iso"` to somewhere easy to access like your Downloads folder
- Attach the copied `.iso` to your vagrant VM (using the CD/DVD pane/button)
- In a console session inside the guest (e.g. using `vagrant ssh`) run:
    sudo mount /dev/cdrom /media/cdrom/
    sudo /media/cdrom/install
- Choose "upgrade" (even though it's a downgrade) and let it run.

**Comment by rtshome** [comment] 2018-11-27 22:33
Confirming my side too. I'm not sure it's a problem of the vagrant plugin.
I opened time ago an issue on parallels website and I had got the usual  "standard" response.
Is anybody of Parallels reading this? :-(

**Comment by stephenreay** [comment] 2018-11-28 11:47
@romankulikov thank you for the quick response. Can you give any ETA for when a fixed version will be available?

**Comment by romankulikov** [comment] 2018-11-28 11:57
You know according to general corporate policies I cannot give any ETA-s publicly.

If none of workarounds suits you well I may try to publish a separate patch to prl_fs source code.

**Comment by stephenreay** [comment] 2018-11-28 12:04
I'm able to run the v13 drivers for myself, that's fine, but I also publish some Vagrant base boxes. I'd rather not do a release and then realise a day later there's an update for v14 drivers.

Thanks again for your efforts on this, it is appreciated.

**Comment by mpdude** [comment] 2018-11-29 14:53
I've seen the problems reported here during the last days. Glad to see it's not me going crazy, but the problems are real :-)

We're considering switching our team from virtualbox + NFS sharing to Parallels because since the last OS X updates, NFS has become terribly slow. Parallels Shared Folders seemed to be able to beat this performance-wise.

However, these bugs are a real showstopper for serious development. This is nothing the usual Parallels support will be able to address, so glad to have @romankulikov here.

So, one additional thing I'd like to report is that new directories created in OS X seem to be "missing" in the VM: That is, when I create a new directory in OS X in a folder that is shared, a simple `ls` in the VM (Linux) will *not* show this directory. *However* it is possible to `cd` into it. Also `rm` works and will remove it on the OS X side as well.

**Comment by mpdude** [comment] 2018-11-29 15:01
@stephenreay Regarding your [downgrade instructions](https://github.com/Parallels/vagrant-parallels/issues/330#issuecomment-442234022) – where/how can I download Parallels 13?

**Comment by mpdude** [comment] 2018-11-29 15:10
@romankulikov File here, in this repo? Or a better place to give this visibility at Parallels?

**Comment by romankulikov** [comment] 2018-11-29 17:24
@mpdude, frankly I don't know. On the one side we have a track of issues in Shared Folders here in vagrant-parallels project. On the other side these issues don't relate directly to the plugin, they are bugs in another product.

@legal90, what do you think?

**Comment by legal90** [comment] 2018-11-29 19:54
@romankulikov I don't mind it to be here, in this GitHub repo, even if the issue is related to Parallels Desktop, not plugin.
Whatever is more convenient for you and other guys from Parallels to track it and communicate with users. 

P.s. I personally prefer GitHub rather than forums from the UX perspective (Markdown, mentioning, etc.)

**Comment by mpdude** [comment] 2018-11-29 20:32
@legal90 and @romankulikov Thanks! I've created #333 as a new issue.

**Comment by stephenreay** [comment] 2018-12-06 09:35
@romankulikov I keep being asked by the Parallels support team to submit technical reports about the underlying issue (which you said was known, and a fix is waiting to be released for) - is there something I can tell them, so they stop asking me to show them details of a bug that is apparently already fixed internally?

**Comment by romankulikov** [comment] 2018-12-06 16:06
@stephenreay , sorry for inconvenience! Our support missed the link on the resolved issue.

**Comment by timurkar** [comment] 2018-12-14 08:41
Great that i found this conversation. See the same problem, fixed by parallels tools v13 install

**Comment by ashgibson** [comment] 2018-12-19 03:50
The v13 tools install also fixed the issue for me. The problem only started happening after upgrading to Parallels v14 and latest version of vagrant-parallels.

**Comment by fenbox** [comment] 2019-01-16 14:00
> The v13 tools install also fixed the issue for me. The problem only started happening after upgrading to Parallels v14 and latest version of vagrant-parallels.

How to install v13 tool? I have upgrading to Parallels v14.

**Comment by stephenreay** [comment] 2019-01-16 14:09
@fenbox see https://github.com/Parallels/vagrant-parallels/issues/330#issuecomment-442234022 for instructions and https://github.com/Parallels/vagrant-parallels/issues/330#issuecomment-442864906 for a direct link to download the v13 tools.

**Comment by huebs** [comment] 2019-01-17 00:45
@stephenreay it seems the installation process has changed. I downloaded the `Parallels Desktop 13` disk image and there's no longer a file located at `/Volumes/Parallels Desktop 13/Parallels Desktop.app/Contents/Resources/Tools/prl-tools-lin.iso`. Instead, `Parallels Desktop.app` has been replaced with an `Install.app` that downloads the application. I decided to just go ahead and downgrade wholesale as that seemed to be my only option. It seems to have solved the issue for the time being.

**Comment by piratadelfuturo** [comment] 2019-01-18 04:08
Why parallels is doing nothing about this, someone has the direct link for parallel tools 13?

**Comment by romankulikov** [comment] 2019-01-18 09:09
@huebs, @piratadelfuturo,

please take a look carefully, better in terminal: `/Volumes/Parallels Desktop 13/Parallels Desktop.app/Contents/Resources/Tools/prl-tools-lin.iso` is still there. Nothing is changed.

**Comment by stephenreay** [comment] 2019-01-18 09:21
Don't forget that if you're using terminal to copy, you need to quote the path, or escape the slashes, e.g.:

`cp /Volumes/Parallels\ Desktop\ 13/Parallels\ Desktop.app/Contents/Resources/Tools/prl-tools-lin.iso ~/` or `cp "/Volumes/Parallels Desktop 13/Parallels Desktop.app/Contents/Resources/Tools/prl-tools-lin.iso" ~/`

If you're using the Finder, you can just hit Go to Folder (Shift-Cmd-G) and enter the path to the directory unquoted/escaped in the dialog that appears: `/Volumes/Parallels Desktop 13/Parallels Desktop.app/Contents/Resources/Tools/` and then drag and drop/Cmd-C etc to copy it.

**Comment by huebs** [comment] 2019-01-18 09:53
@stephenreay I see it now. Very, very sneaky.

For anyone else coming to this, the `/Volumes/Parallels Desktop 13/Parallels Desktop.app` directory is hidden using the extended attribute rather than adding a leading period to the filename. A pro-tip for anyone using macOS Sierra or newer: pressing `Command + Shift + .` will temporarily display all hidden files (both dot and attributed) in the Finder. Press it again to make them disappear again.

**Comment by stephenreay** [comment] 2019-02-07 08:04
I've just today updated Parallels, and now `prltoolsd` reports version `14.1.45476`.

Running the same test I ran earlier now succeeds.

**Comment by dec5e** [comment] 2019-03-26 13:50
Have the same issue. Parallels Desktop v14.1.2 (45479) on MacOS Mojave 10.14.3 (18D109), running Ubuntu 18.04 in Vagrant (box `bento/ubuntu-18.04`).

@romankulikov Is downgrading to Parallels v13 still the only and recommended option?  😞 
Does it have Ubuntu 18.04 support?

**Comment by romankulikov** [comment] 2019-03-27 17:47
@dec5e, what exact issue do you have? This thread contains log of pretty different issues. Some of them are expected to be fixed in 14.1.3.

**Comment by dec5e** [comment] 2019-03-29 10:25
@romankulikov The one described in original description - when running php script I get lots of string in output:
```
PHP Warning: Unexpected character in input: '
```

Here is smallest `Vagrantfile`:
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y php
  SHELL
end
```
Then I created empty `test.php` in same folder and run inside Vagrant - empty output.
After I edit once again with  adding new line I get:
```
vagrant@ubuntu-18:/vagrant$ php test.php
PHP Warning:  Unexpected character in input:  ' in /vagrant/test.php on line 2
``` 
And now every time I add new character in php file on host system, new hidden character is added (?) to the end of the sctipt and produces new line with similar warning.

For example for
```php
<?php

echo "foo";
```
I get
```
vagrant@ubuntu-18:/vagrant$ php test.php
PHP Warning:  Unexpected character in input:  ' in /vagrant/test.php on line 2
PHP Warning:  Unexpected character in input:  ' in /vagrant/test.php on line 2
PHP Warning:  Unexpected character in input:  ' in /vagrant/test.php on line 2
PHP Warning:  Unexpected character in input:  ' in /vagrant/test.php on line 2
PHP Warning:  Unexpected character in input:  ' in /vagrant/test.php on line 2
PHP Warning:  Unexpected character in input:  ' in /vagrant/test.php on line 2
PHP Warning:  Unexpected character in input:  ' in /vagrant/test.php on line 2
PHP Warning:  Unexpected character in input:  ' in /vagrant/test.php on line 2
PHP Warning:  Unexpected character in input:  ' in /vagrant/test.php on line 2
PHP Warning:  Unexpected character in input:  ' in /vagrant/test.php on line 2
PHP Warning:  Unexpected character in input:  ' in /vagrant/test.php on line 2
PHP Warning:  Unexpected character in input:  ' in /vagrant/test.php on line 2
```

And important to mention: similar problem with unexpected extra characters happens not only with php files but withothers too. Here is git for example:
```
vagrant@ubuntu-18:/vagrant$ git status
error: index uses �% extension, which we do not understand
fatal: index file corrupt
vagrant@ubuntu-18:/vagrant$ git diff
error: index uses <B4>%<U+0085> extension, which we do not understand
fatal: index file corrupt
```

Parallels v14.1.3 (45485), Vagrant v2.2.3, vagrant-parallels plugin v2.0.0, MacOS Mojave v10.14.3 (18D109), Vagrant box `bento/ubuntu-18.04` v201812.27.0

**Comment by romankulikov** [comment] 2019-03-29 11:27
@dec5e, please make sure Parallels Tools inside VM are up-to-date also:
```
cat /usr/lib/parallels-tools/version
```

**Comment by mpdude** [comment] 2019-03-29 12:04
By the way, should I expect I/O performance improvements when switching to v14 tools?

**Comment by dec5e** [comment] 2019-03-29 14:09
@romankulikov Yeah, forgot to mention. They are not up-to-date (version is 14.1.0.45387) but I'm not able to update them. Installation is getting stuck, `/var/log/parallels-tools-install.log` is:
```
Started installation of Parallels Guest Tools version '14.1.3.45485'
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:3 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Get:4 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Fetched 88.7 kB in 1s (139 kB/s)
Reading package lists...
Return code from apt-get update is 0
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package libcc1-0:amd64.
(Reading database ... 42958 files and directories currently installed.)
Preparing to unpack .../00-libcc1-0_8.2.0-1ubuntu2~18.04_amd64.deb ...
Unpacking libcc1-0:amd64 (8.2.0-1ubuntu2~18.04) ...
Selecting previously unselected package libgomp1:amd64.
Preparing to unpack .../01-libgomp1_8.2.0-1ubuntu2~18.04_amd64.deb ...
Unpacking libgomp1:amd64 (8.2.0-1ubuntu2~18.04) ...
Selecting previously unselected package libitm1:amd64.
Preparing to unpack .../02-libitm1_8.2.0-1ubuntu2~18.04_amd64.deb ...
Unpacking libitm1:amd64 (8.2.0-1ubuntu2~18.04) ...
Selecting previously unselected package libatomic1:amd64.
Preparing to unpack .../03-libatomic1_8.2.0-1ubuntu2~18.04_amd64.deb ...
Unpacking libatomic1:amd64 (8.2.0-1ubuntu2~18.04) ...
Selecting previously unselected package libasan4:amd64.
Preparing to unpack .../04-libasan4_7.3.0-27ubuntu1~18.04_amd64.deb ...
Unpacking libasan4:amd64 (7.3.0-27ubuntu1~18.04) ...
Selecting previously unselected package liblsan0:amd64.
Preparing to unpack .../05-liblsan0_8.2.0-1ubuntu2~18.04_amd64.deb ...
Unpacking liblsan0:amd64 (8.2.0-1ubuntu2~18.04) ...
Selecting previously unselected package libtsan0:amd64.
Preparing to unpack .../06-libtsan0_8.2.0-1ubuntu2~18.04_amd64.deb ...
Unpacking libtsan0:amd64 (8.2.0-1ubuntu2~18.04) ...
Selecting previously unselected package libubsan0:amd64.
Preparing to unpack .../07-libubsan0_7.3.0-27ubuntu1~18.04_amd64.deb ...
Unpacking libubsan0:amd64 (7.3.0-27ubuntu1~18.04) ...
Selecting previously unselected package libcilkrts5:amd64.
Preparing to unpack .../08-libcilkrts5_7.3.0-27ubuntu1~18.04_amd64.deb ...
Unpacking libcilkrts5:amd64 (7.3.0-27ubuntu1~18.04) ...
Selecting previously unselected package libmpx2:amd64.
Preparing to unpack .../09-libmpx2_8.2.0-1ubuntu2~18.04_amd64.deb ...
Unpacking libmpx2:amd64 (8.2.0-1ubuntu2~18.04) ...
Selecting previously unselected package libquadmath0:amd64.
Preparing to unpack .../10-libquadmath0_8.2.0-1ubuntu2~18.04_amd64.deb ...
Unpacking libquadmath0:amd64 (8.2.0-1ubuntu2~18.04) ...
Selecting previously unselected package libgcc-7-dev:amd64.
Preparing to unpack .../11-libgcc-7-dev_7.3.0-27ubuntu1~18.04_amd64.deb ...
Unpacking libgcc-7-dev:amd64 (7.3.0-27ubuntu1~18.04) ...
Selecting previously unselected package gcc-7.
Preparing to unpack .../12-gcc-7_7.3.0-27ubuntu1~18.04_amd64.deb ...
Unpacking gcc-7 (7.3.0-27ubuntu1~18.04) ...
Selecting previously unselected package gcc.
Preparing to unpack .../13-gcc_4%3a7.3.0-3ubuntu2.1_amd64.deb ...
Unpacking gcc (4:7.3.0-3ubuntu2.1) ...
Setting up libquadmath0:amd64 (8.2.0-1ubuntu2~18.04) ...
Setting up libgomp1:amd64 (8.2.0-1ubuntu2~18.04) ...
Setting up libatomic1:amd64 (8.2.0-1ubuntu2~18.04) ...
Setting up libcc1-0:amd64 (8.2.0-1ubuntu2~18.04) ...
Setting up libasan4:amd64 (7.3.0-27ubuntu1~18.04) ...
Setting up libcilkrts5:amd64 (7.3.0-27ubuntu1~18.04) ...
Setting up libubsan0:amd64 (7.3.0-27ubuntu1~18.04) ...
Setting up libtsan0:amd64 (8.2.0-1ubuntu2~18.04) ...
Setting up liblsan0:amd64 (8.2.0-1ubuntu2~18.04) ...
Setting up libmpx2:amd64 (8.2.0-1ubuntu2~18.04) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Setting up libitm1:amd64 (8.2.0-1ubuntu2~18.04) ...
Setting up libgcc-7-dev:amd64 (7.3.0-27ubuntu1~18.04) ...
Setting up gcc-7 (7.3.0-27ubuntu1~18.04) ...
Setting up gcc (4:7.3.0-3ubuntu2.1) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package linux-headers-4.15.0-29.
(Reading database ... 43256 files and directories currently installed.)
Preparing to unpack .../linux-headers-4.15.0-29_4.15.0-29.31_all.deb ...
Unpacking linux-headers-4.15.0-29 (4.15.0-29.31) ...
Selecting previously unselected package linux-headers-4.15.0-29-generic.
Preparing to unpack .../linux-headers-4.15.0-29-generic_4.15.0-29.31_amd64.deb ...
Unpacking linux-headers-4.15.0-29-generic (4.15.0-29.31) ...
Setting up linux-headers-4.15.0-29 (4.15.0-29.31) ...
Setting up linux-headers-4.15.0-29-generic (4.15.0-29.31) ...
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://security.ubuntu.com/ubuntu bionic-security InRelease
Get:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic-updates/main i386 Packages [479 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [560 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic-updates/universe i386 Packages [737 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [747 kB]
Fetched 2686 kB in 1s (1974 kB/s)
Reading package lists...
Return code from apt-get update is 0
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package libstdc++-7-dev:amd64.
(Reading database ... 72613 files and directories currently installed.)
Preparing to unpack .../00-libstdc++-7-dev_7.3.0-27ubuntu1~18.04_amd64.deb ...
Unpacking libstdc++-7-dev:amd64 (7.3.0-27ubuntu1~18.04) ...
Selecting previously unselected package g++-7.
Preparing to unpack .../01-g++-7_7.3.0-27ubuntu1~18.04_amd64.deb ...
Unpacking g++-7 (7.3.0-27ubuntu1~18.04) ...
Selecting previously unselected package g++.
Preparing to unpack .../02-g++_4%3a7.3.0-3ubuntu2.1_amd64.deb ...
Unpacking g++ (4:7.3.0-3ubuntu2.1) ...
Selecting previously unselected package libdpkg-perl.
Preparing to unpack .../03-libdpkg-perl_1.19.0.5ubuntu2.1_all.deb ...
Unpacking libdpkg-perl (1.19.0.5ubuntu2.1) ...
Selecting previously unselected package dpkg-dev.
Preparing to unpack .../04-dpkg-dev_1.19.0.5ubuntu2.1_all.deb ...
Unpacking dpkg-dev (1.19.0.5ubuntu2.1) ...
Selecting previously unselected package build-essential.
Preparing to unpack .../05-build-essential_12.4ubuntu1_amd64.deb ...
Unpacking build-essential (12.4ubuntu1) ...
Selecting previously unselected package dkms.
Preparing to unpack .../06-dkms_2.3-3ubuntu9.2_all.deb ...
Unpacking dkms (2.3-3ubuntu9.2) ...
Selecting previously unselected package libfakeroot:amd64.
Preparing to unpack .../07-libfakeroot_1.22-2ubuntu1_amd64.deb ...
Unpacking libfakeroot:amd64 (1.22-2ubuntu1) ...
Selecting previously unselected package fakeroot.
Preparing to unpack .../08-fakeroot_1.22-2ubuntu1_amd64.deb ...
Unpacking fakeroot (1.22-2ubuntu1) ...
Selecting previously unselected package libalgorithm-diff-perl.
Preparing to unpack .../09-libalgorithm-diff-perl_1.19.03-1_all.deb ...
Unpacking libalgorithm-diff-perl (1.19.03-1) ...
Selecting previously unselected package libalgorithm-diff-xs-perl.
Preparing to unpack .../10-libalgorithm-diff-xs-perl_0.04-5_amd64.deb ...
Unpacking libalgorithm-diff-xs-perl (0.04-5) ...
Selecting previously unselected package libalgorithm-merge-perl.
Preparing to unpack .../11-libalgorithm-merge-perl_0.08-3_all.deb ...
Unpacking libalgorithm-merge-perl (0.08-3) ...
Selecting previously unselected package libfile-fcntllock-perl.
Preparing to unpack .../12-libfile-fcntllock-perl_0.22-3build2_amd64.deb ...
Unpacking libfile-fcntllock-perl (0.22-3build2) ...
Setting up libdpkg-perl (1.19.0.5ubuntu2.1) ...
Setting up libstdc++-7-dev:amd64 (7.3.0-27ubuntu1~18.04) ...
Setting up libfile-fcntllock-perl (0.22-3build2) ...
Setting up dpkg-dev (1.19.0.5ubuntu2.1) ...
Setting up dkms (2.3-3ubuntu9.2) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Setting up libfakeroot:amd64 (1.22-2ubuntu1) ...
Setting up libalgorithm-diff-perl (1.19.03-1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Setting up g++-7 (7.3.0-27ubuntu1~18.04) ...
Setting up fakeroot (1.22-2ubuntu1) ...
update-alternatives: using /usr/bin/fakeroot-sysv to provide /usr/bin/fakeroot (fakeroot) in auto mode
Setting up libalgorithm-merge-perl (0.08-3) ...
Setting up libalgorithm-diff-xs-perl (0.04-5) ...
Setting up g++ (4:7.3.0-3ubuntu2.1) ...
update-alternatives: using /usr/bin/g++ to provide /usr/bin/c++ (c++) in auto mode
Setting up build-essential (12.4ubuntu1) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Installation of Parallels Guest Tools version '14.1.0.45387' was found.
Created previous version backup in '/tmp/prltools-backup-BNZPgT.tar.gz'

Fri Mar 29 07:12:17 MDT 2019
Start installation or upgrade of Guest Tools
new version of parallels tools
Found Guest Tools directory: /usr/lib/parallels-tools
Umounting Shared Folders: done
Shutting down Parallels tools daemon: done
Started installation of Parallels Guest Tools version '14.1.3.45485'
Installation of Parallels Guest Tools version '14.1.0.45387' was found.
Created previous version backup in '/tmp/prltools-backup-vToe55.tar.gz'

Fri Mar 29 07:23:35 MDT 2019
Start installation or upgrade of Guest Tools
new version of parallels tools
Found Guest Tools directory: /usr/lib/parallels-tools
Umounting Shared Folders: done
Shutting down Parallels tools daemon: done
```

Nothing happens after this, version is still old one.

Any suggestions how to finish this process?

**Comment by romankulikov** [comment] 2019-03-29 15:34
@dec5e, something like this:
1. on the host side attach Guest Tools ISO-image: `$ prlctl installtools $your_vm_name`;
2. on the guest side mount the image and start installation: `# mount /dev/sr0 /mnt && /mnt/install -i`;
3. reboot VM.

**Comment by romankulikov** [comment] 2019-03-29 15:39
@mpdude, well, it highly depends. One of the main features of version 14 in Guest Tools is a fully supported mmap. So if your software has strict dependency on this functionality Guest Tools version 14 is your only option. Speaking about general IO performance of VM (not only through Shared Folders) Guest Tools for Linux don't influence on this.

**Comment by dec5e** [comment] 2019-04-05 11:25
@romankulikov your instructions about updating Parallels Tools worked for me! 👍 

To mention: in second step I had image already mounted:
```bash
$ df -h
Filesystem                       Size  Used Avail Use% Mounted on
...
/dev/loop0                        66M   66M     0 100% /tmp/PrlToolsPackages
```
so I just run installation with
```bash
$ sudo /tmp/PrlToolsPackages/install -i
```

And after updating tools – problem disappeared. Thanks!

**Comment by stephenreay** [comment] 2019-09-22 11:42
I can't believe this, but a variant of this problem has resurfaced in PD15.

I can't reproduce it all the time, and it's no longer showing the file as corrupted, it just doesn't show changes made from the host.

**Comment by stephenreay** [comment] 2019-09-22 11:49
@romankulikov do I need to log this with support to get some traction on it again, or can you reopen the existing issue?

**Comment by romankulikov** [comment] 2019-10-02 17:21
@stephenreay, can you please provide more details about the issue? What guest distro do you use? Can you give a simple reproduction test case (like with with PHP interpreter above)?

**Comment by stephenreay** [comment] 2019-10-02 17:26
I believe it was a Debian9 (maybe Debian 10, which, yeah, PD Support have told me is unsupported still). As I said it's not reliably reproducible - just sometimes, files changed on the host would not show any change at all on the guest - I had to reboot the guest to get it to show the changes.

It also didn't seem to be specific to how the file was opened - everything in the guest was showing the file as unchanged.

I haven't seen it happen in the last few days, I'll reply back if I do though, with more specifics.

**Comment by legal90** [comment] 2022-12-19 15:02
Hi all, 
I'm gonna close this issue since there were no updates for 3+ years. 
Feel free to create a new one if you will face that problem again.

**Closed by legal90** 2022-12-19 15:02 UTC
Labels: upstream/parallels
