### ISSUE TITLE
Cannot connect Hard Drive 0

### ISSUE THREAD

**Issue by johnr-spindance** [Parallels/vagrant-parallels#192] opened 2015-06-12 14:16 UTC
Hello,

I've been trying to create a parallels vagrant box and have run into this error a number of times in the past few days. I've created a parallels box before and haven't had this happen before until recently, it occurs when I create the box with Packer and when I create it manually (doesn't matter how I create it). This is the error:

![image](https://cloud.githubusercontent.com/assets/7714111/8131956/e96beeec-10eb-11e5-877c-b6e9ac593a4e.png)

Do you know what might be causing this?

I'm using this version of the vagrant-parallels plugin: vagrant-parallels (1.3.13)

I'm using this version of Parallels: Version 10.1.3 (28868)

I'm using this version of Vagrant: Installed Version: 1.7.2

Do you have any ideas as to what I might be doing wrong or if this is a known issue? Let me know if I should post any other details to help.

Much Appreciated,

John

**Comment by legal90** [comment] 2015-06-12 14:30
@johnr-spindance  Could you please describe how are you building boxes (provide Packer template, commands)?

Seems like you run into one of known issues:
Either in Packer: https://github.com/mitchellh/packer/issues/1590  (not fixed)
or in Vagrant: https://github.com/mitchellh/vagrant/issues/5657 (will be fixed in the next Vagrant release)

**Comment by johnr-spindance** [comment] 2015-06-12 14:38
@legal90 Thanks for replying so quickly!

This is the builder I'm using with Packer:

```

    "type": "parallels-windows-iso",
    "guest_os_type": "win-2012",
    "parallels_tools_flavor": "win",
    "hard_drive_interface": "sata",
    "iso_url": "file:///Users/johnr/Downloads/en_windows_server_2012_r2_x64_dvd_2707946.iso",
    "iso_checksum_type": "md5",
    "iso_checksum": "0e7c09aab20dec3cd7eab236dab90e78",
    "boot_wait": "2m",
    "winrm_username": "vagrant",
    "winrm_password": "vagrant",
    "winrm_wait_timeout": "10m",
    "shutdown_timeout": "1h",
    "shutdown_command": "shutdown /s /t 10 /f /d p:4:1 /c \"Packer Shutdown\"",
    "disk_size": "61440",
    "floppy_files": [
       "./answer_files/2012_r2/parallels/Autounattend.xml"
    ],
    "prlctl": [
      ["set", "{{.Name}}", "--memsize", "2048"],
      ["set", "{{.Name}}", "--cpus", "2"]
    ]
  }
```

This is the post-processor:

```
{
    "type": "vagrant",
    "output": "spin-win2012r2_parallels.box",
    "vagrantfile_template": "vagrant_templates/vagrant.parallels-win2012r2.template",
    "only": ["parallels-windows-iso"]
  }
```

This is the template (Which I suspect could be the problem):
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.6.2"

Vagrant.configure("2") do |config|
    config.vm.define "vagrant-windows-2012-r2"
    config.vm.box = "windows_2012_r2"
    config.vm.communicator = "winrm"

    # Admin user name and password
    config.winrm.username = "vagrant"
    config.winrm.password = "vagrant"

    config.vm.guest = :windows
    config.windows.halt_timeout = 15
end
```

I wasn't sure how the vagrant template needed to be created. Since I'm using these vagrant boxes with testkitchen, I wasn't sure how picky I had to be because I believe testkitchen uses its own vagrant configurations. I'm using testkitchen with parallels. This is my .kitchen.yml config (in case you want to see that too):

```
---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_path: "test/shared"

platforms:
  - name: windows-2012
    driver:
      box: spin-win2012r2-virtualbox
      provider: virtualbox
    driver_config:
      communicator: winrm
      vm_hostname: false
```

**Comment by johnr-spindance** [comment] 2015-06-12 14:50
I looked at the issues you referenced. They are interesting. This may help too (the directory structure of the box in ~/.vagrant.d/boxes/spin-win2012r2-parallels:

```
Mac000147s-MacBook-Pro-2:spin-win2012r2-parallels johnr$ tree
.
└── 0
    └── parallels
        ├── Vagrantfile
        ├── harddisk1.hdd.0.{5fbaabe3-6958-40ff-92a7-860e329aab41}.hds
        ├── metadata.json
        └── packer-parallels-windows-iso.pvm
            ├── NVRAM.dat
            ├── VmInfo.pvi
            ├── config.pvs
            ├── config.pvs.backup
            ├── floppy.fdd
            └── harddisk1.hdd
                ├── DiskDescriptor.xml
                ├── harddisk1.hdd
                └── harddisk1.hdd.drh

4 directories, 11 files
```

**Comment by legal90** [comment] 2015-06-12 14:51
Hm... Then please, show the content of your box directory. The output of these commands will be enough (paths can be a little bit different):
```bash
ls -la ~/.vagrant.d/boxes/spin-win2012r2-parallels/0/parallels/
ls -la ~/.vagrant.d/boxes/spin-win2012r2-parallels/0/parallels/*.pvm/
ls -la ~/.vagrant.d/boxes/spin-win2012r2-parallels/0/parallels/*.pvm/*.hdd
```

Also, please tell what Packer version are you using? (`packer version`)

**Comment by johnr-spindance** [comment] 2015-06-12 14:52
```
Mac000147s-MacBook-Pro-2:test4 johnr$ packer version
Packer v0.7.5
```

**Comment by johnr-spindance** [comment] 2015-06-12 15:03
@legal90 Is there a workaround that you know of with the packer bug? Possibly just naming the build so it doesn't hit that 100 character limit?

**Comment by johnr-spindance** [comment] 2015-06-12 15:05
maybe not... if its naming it as ./0/parallels/packer-parallels-windows-iso.pvm/harddisk1.hdd.0.{5fbaabe3-6958-40ff-92a7-860e329aab41}.hds

**Comment by legal90** [comment] 2015-06-12 15:30
Yes, this is actually caused by the `tar` library bug which I have described in mitchellh/packer#1590
Unfortunately, I have not reported it to the library maintainers yet. 

So, you can work it around "on the place" by moving `harddisk1.hdd.0.{5fbaabe3-6958-40ff-92a7-860e329aab41}.hds` to the `packer-parallels-windows-iso.pvm/harddisk1.hdd`

To fix it in the Packer's template.json you should add a short "vm_name" there, for example:
```
"vm_name": "parallels-win-box"
```
Currently you have the name "packer-parallels-windows-iso" and there are 105 symbols in the path:
```
packer-parallels-windows-iso.pvm/harddisk1.hdd/harddisk1.hdd.0.{5fbaabe3-6958-40ff-92a7-860e329aab41}.hds
```

But with "parallels-win-box" name there will be 94 symbols.

P.s. I see that you are using a special Packer builder type in the example above: `type: parallels-windows-iso`. Is it some 3rd party plugin or your custom builder?

**Comment by johnr-spindance** [comment] 2015-06-12 15:43
I'm using these plugins, which seem to work really well because they give me the WinRM capabilities I need without the need of installing OpenSSH on Windows:

https://github.com/packer-community/packer-windows-plugins

**Comment by johnr-spindance** [comment] 2015-06-12 15:59
@legal90 It worked!

I'm going to say that this is definitely an issue with the 100 character limit. Even outside of packer, I was failing to get this to work - manually packaging and getting the exact same results. It was because I was naming the VM too long in parallels...

Thank you for the workaround and for your work on this bug!

Cheers!

**Closed** 2015-06-12 16:17 UTC
