### ISSUE TITLE
PrlHandle_FromString: Invalid argument. An invalid argument was passed

### ISSUE THREAD

**Issue by luc-lynx** [Parallels/vagrant-parallels#326] opened 2018-09-01 20:07 UTC
**Problem description:**

I'm trying to use vagrant with parallels and I've run up against the following error:

```
$ vagrant up --provider=parallels
The provider 'parallels' that was requested to back the machine
'master' is reporting that it isn't usable on this system. The
reason is shown below:

There was an error while command execution. The command and stderr is shown below.

Command: ["/usr/local/bin/prlsrvctl", "info", "--license", "--json"]

Stderr: PrlHandle_FromString: Invalid argument. An invalid argument was passed.
```
**System info:**
Mac OS High Sierra 10.13.6 (17G65)

**Parallels Version:**
Parallels Desktop for Mac Business Edition, Version 13.3.2 (43368)

**Additional info:**

And indeed, it I type manually the following command:

```
$ /usr/local/bin/prlsrvctl info --license --json
PrlHandle_FromString: Invalid argument. An invalid argument was passed.
```

I'm getting the same error.

**Comment by luc-lynx** [comment] 2018-09-01 20:42
Updated my Parallels to 14 but the problem remained

**Comment by legal90** [comment] 2018-09-03 06:43
It seems like an issue of license activation. 
Pinging @alevlasu, @romankulikov - we might meed your assistance here.

**Comment by romankulikov** [comment] 2018-09-03 13:47
@luc-lynx, could you please reproduce the problem, generate problem report (`prlsrvctl problem-report --send`) and post its id here.

**Comment by romankulikov** [comment] 2018-09-07 18:10
> [22:17:45] $ prlsrvctl problem-report --send
> PrlHandle_FromString: Invalid argument. An invalid argument was passed.

Ok. Try this command instead:
```
/Applications/Parallels\ Desktop.app/Contents/MacOS/prlsrvctl problem-report --send --stand-alone
```

**Comment by luc-lynx** [comment] 2018-09-12 08:35
```The problem report was successfully sent with id: 275119399```

**Comment by luc-lynx** [comment] 2018-09-17 09:17
Any updates?

**Comment by romankulikov** [comment] 2018-09-17 18:07
@luc-lynx, can you please try to re-activate Parallels Desktop? Make sure you have the valid license key beforehand. Then you should:
1. stop the product:
```
$ killall prl_client_app && sudo launchctl stop com.parallels.desktop.launchdaemon
```
2. remove license file:
```
$ sudo rm /Library/Preferences/Parallels/licenses.xml
```
3. start Parallels Desktop again and enter valid license key.

**Comment by legal90** [comment] 2018-10-21 13:40
@luc-lynx Does that issue still exist for you?

**Comment by luc-lynx** [comment] 2018-10-25 20:46
I'm sorry for the delay, I'll get back shortly

**Comment by legal90** [comment] 2020-04-26 08:38
I'm gonna close this issue since it's pretty old and wasn't updated for more than a year.

If anyone still have it on the latest versions of Parallels Desktop, Vagrant and the provider, feel free to open a new issue for that.

**Closed by legal90** 2020-04-26 08:38 UTC
Labels: upstream/parallels
