### ISSUE TITLE
Install of Parallels Guest Tools fails

### ISSUE THREAD

**Issue by SunSparc** [Parallels/vagrant-parallels#175] opened 2015-02-19 17:35 UTC
Trying to "up" a new boxcutter Ubuntu 14.04 box on my Mac. It gets the box started and then starts provisioning and seems to fail with when it reaches the Parallels Tools install. Not sure if this is a boxcutter problem or a Parallels problem or perhaps even user error. :)

Here is the listing from my launch of the vagrant:

    $ vagrant up
    Bringing machine 'default' up with 'parallels' provider...
    ==> default: Importing base box 'boxcutter/ubuntu1404'...
    ==> default: Checking if box 'boxcutter/ubuntu1404' is up to date...
    ==> default: Setting the name of the VM: [name_obfuscated]
    ==> default: Preparing network interfaces based on configuration...
        default: Adapter 0: shared
    ==> default: Clearing any previously set network interfaces...
    ==> default: Forwarding ports...
    ==> default: Running 'pre-boot' VM customizations...
    ==> default: Booting VM...
    ==> default: Waiting for machine to boot. This may take a few minutes...
        default: SSH address: 10.211.55.16:22
        default: SSH username: vagrant
        default: SSH auth method: private key
        default:
        default: Vagrant insecure key detected. Vagrant will automatically replace
        default: this with a newly generated keypair for better security.
        default:
        default: Inserting generated public key within guest...
        default: Removing insecure key from the guest if its present...
        default: Key inserted! Disconnecting and reconnecting using new SSH key...
    ==> default: Machine booted and ready!
    ==> default: Checking for Parallels Tools installed on the VM...
    ==> default: Parallels Tools installed on this VM are outdated! In most cases
    ==> default: this is fine but in rare cases it can cause things such as shared
    ==> default: folders to not work properly. If you see shared folder errors,
    ==> default: please update Parallels Tools within the virtual machine and
    ==> default: reload your VM.
    ==> default: Installing the proper version of Parallels Tools. This may take a few minutes...
    The following SSH command responded with a non-zero exit status.
    Vagrant assumes that this means the command failed!

    ptiagent-cmd --info

    Stdout from the command:

    Stderr from the command:

    stdin: is not a tty

From the file `/var/log/parallels-tools-install.log` in the newly launched vagrant:

	Start installation or upgrade of Guest Tools
	new version of parallels tools
	Installed Guest Tools were not found
	Perform installation into the /usr/lib/parallels-tools directory
	cat: /usr/lib/parallels-tools/kmods/../version: No such file or directory
	Start installation of prl_eth kernel module
	awk: cannot open /lib/modules/3.13.0-32-generic/build/include/generated/uapi/linux/version.h (No such file or directory)
	/bin/sh: 1: [: -ge: unexpected operator
	make: Entering directory `/usr/lib/parallels-tools/kmods'
	cd prl_eth/pvmnet && make
	awk: cannot open /lib/modules/3.13.0-32-generic/build/include/generated/uapi/linux/version.h (No such file or directory)
	/bin/sh: 1: [: -ge: unexpected operator
	/bin/sh: 1: [: -ge: unexpected operator
	make[1]: Entering directory `/usr/lib/parallels-tools/kmods/prl_eth/pvmnet'
	Makefile:47: *** Unsupported kernel version  in /lib/modules/3.13.0-32-generic/build.  Stop.
	make[1]: Leaving directory `/usr/lib/parallels-tools/kmods/prl_eth/pvmnet'
	make: *** [installme] Error 2
	make: Leaving directory `/usr/lib/parallels-tools/kmods'
	Error: could not build kernel modules
	Error: failed to install kernel modules

I have halted and destroyed multiple times. This happens each time. I have also tried 'boxcutter/ubuntu1410' with the same results.

**Comment by SunSparc** [comment] 2015-02-19 21:30
For now I have commented out the `v.update_guest_tools = true` line in my Vagrant files, and the vagrants work fine. But this just steps over the problem and guest tools are not being updated.

**Comment by legal90** [comment] 2015-02-19 21:39
@SunSparc Thanks for a report. Currently "boxcutter/ubuntu1410" has the latest Parallels Tools at this moment - version 10.1.3
What Parallels Desktop version are you using? You can check it by `prlctl --version`

**Comment by SunSparc** [comment] 2015-02-19 21:48
@legal90 my `prlctl --version` shows: `prlctl version 10.1.4 (28883) rev 0`

**Comment by legal90** [comment] 2015-02-20 00:05
Ah, seems like it is Parallels Desktop problem. It will be investigated by Parallels.

@SunSparc I can also recommend you to try this box: ["parallels/ubuntu-14.04"](https://atlas.hashicorp.com/parallels/boxes/ubuntu-14.04). There are an older Parallels Tools version yet (10.1.2), but it could be successfully updated to the 10.1.4, without the error you've mentioned above.

**Comment by SunSparc** [comment] 2015-02-20 17:40
Thank you for the response and the information.

**Comment by joliver** [comment] 2015-02-20 17:45
At present, simply changing `v.update_guest_tools = true` to `v.update_guest_tools = false` fixes it.

**Comment by legal90** [comment] 2015-03-03 16:44
@SunSparc 'boxcutter/ubuntu1404' has been recently updated. In the box version 1.0.14 there are Parallels Tools v10.1.4 installed:
https://atlas.hashicorp.com/boxcutter/boxes/ubuntu1404

**Comment by joliver** [comment] 2015-03-03 16:46
I saw this as well, but doesn't this just "kick the can down the road"? In other words, when the next update of Parallels happens, won't the tools have the same problem?

**Comment by legal90** [comment] 2015-03-03 20:23
We've investigated an issue and fortunately, it is not due to Parallels Desktop overall. 
It affects only users of `boxcutter/ubuntu*` boxes and it's caused by the fact that `linux-headers*` packages are not deleted gracefully in these boxes.

I've reported this problem to box maintainers and also provided a possible solutions: https://github.com/boxcutter/ubuntu/issues/5
So, Parallels Tools update will be failed regardless of Parallels Desktop version, until the issue is fixed in boxcutter and boxes are rebuilt again. But I hope it happens soon.

**Closed by legal90** 2015-03-03 20:23 UTC
Labels: bug

**Comment by legal90** [comment] 2015-03-03 20:26
As I said before, our official boxes are not affected by this: https://atlas.hashicorp.com/parallels/boxes/

**Comment by SunSparc** [comment] 2015-03-03 23:08
@legal90 Thank you for looking into this for us.

**Comment by wizonesolutions** [comment] 2015-08-13 17:03
I use `parallels/centos-6.6`, and it IS affected by this. I am on `1.0.4`. Does that box still get tools updates?

**Comment by wizonesolutions** [comment] 2015-08-13 17:38
@legal90 Figured it out. Outdated kernel in the VM, but the `kernel-devel` package the Guest Tools try to install is apparently not available in the repositories anymore. Something like that. Maybe `parallels/centos-6.6` needs an update?

**Comment by legal90** [comment] 2015-08-17 18:00
@wizonesolutions I've just updated all `parallels/*` boxes. Now they have Parallels Tools 10.2.2

**Comment by danemacmillan** [comment] 2016-09-26 18:55
This is still happening. I've disabled the update config from the `VagrantFile` and it works. This is on `parallels/6.7`.
